### ISSUE TITLE
0x11singh99 - In modifier `permitSender` according to `EIP712` specification wrong typeHash used in hashStruct calculation, missing `uint256 nonce` parameter in typeHash calculation.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-07-exactly-stacking-contracts-judging#67]
0x11singh99

Medium

# In modifier `permitSender` according to `EIP712` specification wrong typeHash used in hashStruct calculation, missing `uint256 nonce` parameter in typeHash calculation.

## Summary

In modifier `permitSender` according to `EIP712` specification wrong `typeHash` used in `hashStruct` calculation, missing `uint256 nonce` parameter in typeHash calculation.

## Vulnerability Details

The `permitSender` modifier in the `RewardsController` contract computes the message hash using a method that deviates from the [EIP-712 standard](https://eips.ethereum.org/EIPS/eip-712#definition-of-hashstruct). Specifically the hashStruct construction includes a `nonce` parameter that is not defined in `typeHash` used in encoding data as per EIP-712 specifications.
This will cause calculating wrong `hashStruct` and finally creating wrong digest hash. This inconsistency will lead to interoperability issues and could affect the proper validation of signatures across different platforms and tools that rely on EIP-712.
`typeHash` and `hashStruct` are defined in [EIP-712 standard](https://eips.ethereum.org/EIPS/eip-712#definition-of-hashstruct)

[RewardsController.sol#L774-L798](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/RewardsController.sol#L774-L798)

```solidity
File : contracts/RewardsController.sol

774:  modifier permitSender(ClaimPermit calldata permit) {
775:    assert(_claimSender == address(0));
776:    assert(permit.deadline >= block.timestamp);
777:    unchecked {
778:      address recoveredAddress = ecrecover(
779:        keccak256(
780:          abi.encodePacked(
781:            "\x19\x01",
782:            DOMAIN_SEPARATOR(),
783:            keccak256(
784:              abi.encode(
785:                keccak256("ClaimPermit(address owner,address spender,address[] assets,uint256 deadline)"),//@audit missing nonce parameter which is included in encoded parameters
786:                permit.owner,
787:                msg.sender,
788:                permit.assets,
789:                nonces[permit.owner]++,
790:                permit.deadline
791:              )
792:            )
793:          )
794:        ),
795:        permit.v,
796:        permit.r,
797:        permit.s
798:      );

```

Here we can clearly see the typeHash used here is `keccak256("ClaimPermit(address owner,address spender,address[] assets,uint256 deadline)")` doesn't have `nonce` parameter which is included in encoded parameters just before `permit.deadline` parameter.
So this typeHash calculation is wrong due to missed parameter which will cause finally creating the wrong hash according to EIP712 specification.

## Impact

Due to missed missed nonce parameter `typeHash` will be wrongly calculated which will cause finally creating the wrong hash according to EIP712 specification.

## Tools Used

Manual Review

## Recommendations

Use `uint256 nonce` parameter in calculating `typeHash` when calculating `hashStruct` like below in `permitSender` modifier.

```diff
File : contracts/RewardsController.sol

774:  modifier permitSender(ClaimPermit calldata permit) {
775:    assert(_claimSender == address(0));
776:    assert(permit.deadline >= block.timestamp);
777:    unchecked {
778:      address recoveredAddress = ecrecover(
779:        keccak256(
780:          abi.encodePacked(
781:            "\x19\x01",
782:            DOMAIN_SEPARATOR(),
783:            keccak256(
784:              abi.encode(
- 785:                keccak256("ClaimPermit(address owner,address spender,address[] assets,uint256 deadline)"),
+ 785:                keccak256("ClaimPermit(address owner,address spender,address[] assets,uint256 nonce,uint256 deadline)"),
786:                permit.owner,
787:                msg.sender,
788:                permit.assets,
789:                nonces[permit.owner]++,
790:                permit.deadline
791:              )
792:            )
793:          )
794:        ),
795:        permit.v,
796:        permit.r,
797:        permit.s
798:      );

```

**Comment by thenua3bhai** [comment]
Escalate

Hi @z3s, It is not just assuming. This is very obvious they are using EIP-712 standard to obtain the hash of the message to be signed. We can see ["\x19\x01"](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/RewardsController.sol#L781) prefix in digest where [01](https://eips.ethereum.org/EIPS/eip-191#registry-of-version-bytes) is clearly specifying the EIP712 standard. Also they are using EIP712 [domain separator](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/RewardsController.sol#L759) which also shows they are using EIP712 standard.
Here hashStruct includes a param `nonce`  but it's not in typeHash used for it so it's clearly a bug.

This is famous valid medium bug not compliance with EIP712 when using that standard to hash the message to be signed.
Generally protocol don't explicitly mentions in ReadMe compliance with EIP712 when using. it is obvious by seeing to get message hash. In many previous contests on various platforms this type of bug is considered valid medium even when it is not explicitly stated in readMe to follow EIP712. For example you can see here on codehawks [readMe](https://github.com/Cyfrin/2024-05-beanstalk-the-finale?tab=readme-ov-file#compatibilities) EIP compatibilities it is not explicitly mentioned to compatible with eip712 but still the [bug](https://codehawks.cyfrin.io/c/2024-05-beanstalk-the-finale/s/228) is considered valid medium. And like that there are many bugs in previous contests
ReadMe states only those kind of EIP standards on which contracts structure is based. Like EIP20,EIP1155 or EIP4626.

Thanks

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Hi @z3s, It is not just assuming. This is very obvious they are using EIP-712 standard to obtain the hash of the message to be signed. We can see ["\x19\x01"](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/RewardsController.sol#L781) prefix in digest where [01](https://eips.ethereum.org/EIPS/eip-191#registry-of-version-bytes) is clearly specifying the EIP712 standard. Also they are using EIP712 [domain separator](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/RewardsController.sol#L759) which also shows they are using EIP712 standard.
> Here hashStruct includes a param `nonce`  but it's not in typeHash used for it so it's clearly a bug.
> 
> This is famous valid medium bug not compliance with EIP712 when using that standard to hash the message to be signed.
> Generally protocol don't explicitly mentions in ReadMe compliance with EIP712 when using. it is obvious by seeing to get message hash. In many previous contests on various platforms this type of bug is considered valid medium even when it is not explicitly stated in readMe to follow EIP712. For example you can see here on codehawks [readMe](https://github.com/Cyfrin/2024-05-beanstalk-the-finale?tab=readme-ov-file#compatibilities) EIP compatibilities it is not explicitly mentioned to compatible with eip712 but still the [bug](https://codehawks.cyfrin.io/c/2024-05-beanstalk-the-finale/s/228) is considered valid medium. And like that there are many bugs in previous contests
> ReadMe states only those kind of EIP standards on which contracts structure is based. Like EIP20,EIP1155 or EIP4626.
> 
> Thanks
> 
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
