### ISSUE TITLE
cholakov - `permitAndDeposit` is allowed to be called by the permit creator only

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-exactly-stacking-contracts-judging#85]
cholakov

Medium

# `permitAndDeposit` is allowed to be called by the permit creator only

## Summary

The [`permitAndDeposit`](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4) function is allowed to be called by the permit creator only. Not any other contracts will be able to execute these function on behalf of signer.

## Vulnerability Detail

The [`permitAndDeposit`](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4) function is meant to permit a spender and deposits assets in a single transaction:

https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4
```solidity
function permitAndDeposit(uint256 assets, address receiver, Permit calldata p) external returns (uint256) {
    IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s);
    return deposit(assets, receiver);
  }
```

This function calls OZ's `permit` and passes `msg.sender` as `owner` to that function:

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/extensions/ERC20PermitUpgradeable.sol#L49C5-L72C6
```solidity
function permit(
        address owner,
        address spender,
        uint256 value,
        uint256 deadline,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) public virtual {
        if (block.timestamp > deadline) {
            revert ERC2612ExpiredSignature(deadline);
        }

        bytes32 structHash = keccak256(abi.encode(PERMIT_TYPEHASH, owner, spender, value, _useNonce(owner), deadline));

        bytes32 hash = _hashTypedDataV4(structHash);

        address signer = ECDSA.recover(hash, v, r, s);
        if (signer != owner) {
            revert ERC2612InvalidSigner(signer, owner);
        }

        _approve(owner, spender, value);
    }
```

This means, that the signer can be only the same person that called [`permitAndDeposit`](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4) function.

However, the purpose of the permit is to allow someone to sign the approve signature, so that this signature can be used by another contract to call some function on behalf of signer.

## Impact

[`permitAndDeposit`](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4) is allowed to be called by the permit creator only.

## Code Snippet

https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts/blob/main/protocol/contracts/StakedEXA.sol#L173C2-L176C4
```solidity
function permitAndDeposit(uint256 assets, address receiver, Permit calldata p) external returns (uint256) {
    IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s);
    return deposit(assets, receiver);
  }
```

## Tool used

Manual Review

## Recommendation

Use `receiver` instead of `msg.sender`:
```diff
function permitAndDeposit(uint256 assets, address receiver, Permit calldata p) external returns (uint256) {
    -IERC20Permit(asset()).permit(msg.sender, address(this), p.value, p.deadline, p.v, p.r, p.s);
    +IERC20Permit(asset()).permit(receiver, address(this), p.value, p.deadline, p.v, p.r, p.s);
    return deposit(assets, receiver);
  }
```

**Comment by santiellena** [comment]
Escalate.

This issue deserves Low severity.
The criteria for Medium severity issues if there isn't loss of funds is the following:
```
2. Breaks core contract functionality, rendering the contract useless or leading to loss of funds.
```
However, this issue doesn't show how **core** contract functionality is broken. User is still able to deposit in the `StakedEXA` contract.

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> This issue deserves Low severity.
> The criteria for Medium severity issues if there isn't loss of funds is the following:
> ```
> 2. Breaks core contract functionality, rendering the contract useless or leading to loss of funds.
> ```
> However, this issue doesn't show how **core** contract functionality is broken. User is still able to deposit in the `StakedEXA` contract.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cholakovvv** [comment]
Actually, it is a valid Medium Severity issue, as the primary usage of the permit function introduced in the EIP2612 is to allow users to modify token allowances through a signed message instead of requiring an on-chain transaction initiated by msg.sender, which would potentially break core contract functionality.

I obtained this information from the [EIP2612](https://eips.ethereum.org/EIPS/eip-2612) documentation. 

Here is an example of a previously validated issue on the same exact topic: https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git

**Comment by goheesheng** [comment]
> Actually, it is a valid Medium Severity issue, as the primary usage of the permit function introduced in the EIP2612 is to allow users to modify token allowances through a signed message instead of requiring an on-chain transaction initiated by msg.sender, which would potentially break core contract functionality.
> 
> I obtained this information from the [EIP2612](https://eips.ethereum.org/EIPS/eip-2612) documentation.
> 
> Here is an example of a previously validated issue on the same exact topic: https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git

You are right, but the problem is in the README.md:
> Is the codebase expected to comply with any EIPs? Can there be/are there any deviations from the specification?
No

Stating `would potentially break core contract functionality.` and argument from EIP2612 is invalid because README is the highest hierarchy of truth and there wasn't explicit rules following EIP2612. Furthermore, there isn't any loss of funds.

This should be low at best.

**Comment by the-first-elder** [comment]
> > Actually, it is a valid Medium Severity issue, as the primary usage of the permit function introduced in the EIP2612 is to allow users to modify token allowances through a signed message instead of requiring an on-chain transaction initiated by msg.sender, which would potentially break core contract functionality.
> > I obtained this information from the [EIP2612](https://eips.ethereum.org/EIPS/eip-2612) documentation.
> > Here is an example of a previously validated issue on the same exact topic: https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git
> 
> You are right, but the problem is in the README.md:
> 
> > Is the codebase expected to comply with any EIPs? Can there be/are there any deviations from the specification?
> > No
> 
> Stating `would potentially break core contract functionality.` and argument from EIP2612 is invalid because README is the highest hierarchy of truth and there wasn't explicit rules following EIP2612. Furthermore, there isn't any loss of funds.
> 
> This should be low at best.

As there  was no explicit rules following EIP2613. According to Sherlock rules 

` Hierarchy of truth: If the protocol team provides no specific information, the default rules apply `

Secondly, the purpose of the permit is to allow someone to sign the approve signature, so that this signature can be used by another contract to call some function on behalf of signer.

In this case, anyone should be able to sign permit for the vault, and vault should check that _receiver is same who signed permit.

Looks a valid medium to me.

**Comment by santiellena** [comment]
> Actually, it is a valid Medium Severity issue, as the primary usage of the permit function introduced in the EIP2612 is to allow users to modify token allowances through a signed message instead of requiring an on-chain transaction initiated by msg.sender, which would potentially break core contract functionality.
> 
> I obtained this information from the [EIP2612](https://eips.ethereum.org/EIPS/eip-2612) documentation.
> 
> Here is an example of a previously validated issue on the same exact topic: https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git

@cholakovvv I don't get how not following an EIP which wasn't explicitly mentioned in the README would break core functionality. The user is still able to use the protocol without extensive limitations. 

As for EIPs rules on Sherlock:

## [VII. List of Issue categories that are not considered valid:](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md#vii-list-of-issue-categories-that-are-not-considered-valid)

12. **EIP compliance with no integrations:** If the protocol does not have external integrations then issues related to code not fully complying with the EIP it is implementing and there are no adverse effects of this, are considered informational

**Comment by goheesheng** [comment]
> 12\. **EIP compliance with no integrations:** If the protocol does not have external integrations then issues related to code not fully complying with the EIP it is implementing and there are no adverse effects of this, are considered informational

You further proved my point. This would be an interesting debate within the judges.

**Comment by DevPelz** [comment]
> > Actually, it is a valid Medium Severity issue, as the primary usage of the permit function introduced in the EIP2612 is to allow users to modify token allowances through a signed message instead of requiring an on-chain transaction initiated by msg.sender, which would potentially break core contract functionality.
> 
> > 
> 
> > I obtained this information from the [EIP2612](https://eips.ethereum.org/EIPS/eip-2612) documentation.
> 
> > 
> 
> > Here is an example of a previously validated issue on the same exact topic: https://solodit.xyz/issues/m-25-depositwithpermit-and-mintwithpermit-are-allowed-to-be-called-by-the-permit-creator-only-code4rena-pooltogether-pooltogether-git
> 
> 
> 
> @cholakovvv I don't get how not following an EIP which wasn't explicitly mentioned in the README would break core functionality. The user is still able to use the protocol without extensive limitations. 
> 
> 
> 
> As for EIPs rules on Sherlock:
> 
> 
> 
> ## [VII. List of Issue categories that are not considered valid:](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md#vii-list-of-issue-categories-that-are-not-considered-valid)
> 
> 
> 
> 12. **EIP compliance with no integrations:** If the protocol does not have external integrations then issues related to code not fully complying with the EIP it is implementing and there are no adverse effects of this, are considered informational

@santiellena I believe you do not understand the issue here, let me explain. The permit function's purpose is to allow someone to sign an approve signature, so that this signature can be used by another user(contract / users) to call a certain function on behalf of the signer. However in this case of the depositWithPermit function, only the signer can call the function successfully which in turn breaks the intentions of the function(breaks functionality) cause imagine i sign a message giving approval for someone to help me perform an action but when someone tries it, it would revert cause even though i provided a valid signature im the only one who can perform the action successfully and in the case of this function. It means the function is useless. If it remains this way. So a medium seems right for this.

**Comment by SakshamGuruji3** [comment]
I don't get how this is a security issue , no users will be harmed + no funds lost there is actually no "security" impact here , all the debate is that the functionality is broken , but what's the security impact? Is there a sherlock rule that says " broken functionality with 0 impact is valid"

**Comment by WangSecurity** [comment]
I agree this is indeed a low severity issue. The users are still able to deposit and freely use the protocol, while indeed they cannot ask others to deposit on their behalf. Still, I don't think it constitutes medium severity.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santiellena](https://github.com/sherlock-audit/2024-07-exactly-stacking-contracts-judging/issues/85/#issuecomment-2278650649): accepted

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/exactly/protocol/pull/760

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
